# Generated by Django 4.1.7 on 2023-02-16 19:19

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialbook', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.CharField, to='socialbook.profile'),
        ),
    ]
